# Generated by Django 3.2 on 2022-06-16 12:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220613_0241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'about'},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name_plural': 'blogpost'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'category'},
        ),
        migrations.AlterModelOptions(
            name='certification',
            options={'verbose_name_plural': 'certification'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'contact'},
        ),
        migrations.AlterModelOptions(
            name='contactform',
            options={'verbose_name_plural': 'contactform'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name_plural': 'education'},
        ),
        migrations.AlterModelOptions(
            name='hero',
            options={'verbose_name_plural': 'hero'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name_plural': 'portfolio'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name_plural': 'skills'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'tag'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
